---
  - name: INSTALL-NGINX | Install epel-release
    yum:
      name: epel-release
      state: present

  - name: INSTALL-NGINX | Install nginx
    yum:
      name: nginx
      state: present

  - name: INSTALL-NGINX | selinux httpd_t
    selinux_permissive:
      name: httpd_t
      permissive: true

  - name: INSTALL-NGINX | selinux httpd_can_network_connect
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes

  - name: INSTALL-NGINX | copy nginx.conf
    copy:
      src: files/nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root

  - name: INSTALL-NGINX | Enable and start nginx
    service:
      name: nginx
      state: started
      enabled: yes
