FROM golang:alpine3.17

WORKDIR /usr/src/app

COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy all files to /usr/src/app
COPY . .

EXPOSE 8080

# Build into a executable single file
RUN go build -o /t1cg-forum .

CMD [ "/t1cg-forum" ]