apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  ports:
  - name: {{ .Release.Name }}-mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-mongodb